  - name: install maven
    package:
      name: maven
      state: present

  - name: add system user
    import_role:
      name: common
      tasks_from: add_user
 
  - name: add and remove directory
    import_role:
      name: common
      tasks_from: add_remove

  - name: install mvn package
    command: mvn clean package
    args:
      chdir: /app
  - name: change location and rename
    command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app
  - name: copy the servic file
    import_role:
      name: common
      tasks_from: servicefilecopy
  - name: install mysql
    package:  
      name: mysql
      state: present
  - name: install python dependencies
    pip:
      name: PyMySQL
      executable: pip3.9
      
  - name: load mysql data
    community.mysql.mysql_db:
      state: import
      name: all
      login_user: root
      login_password: "{{ PASSWORD }}"
      login_host: "{{ MYSQL_HOST }}"
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql
  - name: daemon_reload
    import_role: 
      name: common
      tasks_from: demon_servic
