[local]
localhost

[catalogue]
catalogue.sudhakar.shop

[cart]
cart.sudhakar.shop

[user]
user.sudhakar.shop

[shipping]
shipping.sudhakar.shop

[payment]
payment.sudhakar.shop

[mongodb]
mongodb.sudhakar.shop

[redis]
redis.sudhakar.shop

[mysql]
mysql.sudhakar.shop

[rabbitmq]
rabbitmq.sudhakar.shop

[frontend]
frontend.sudhakar.shop
