  - name: import thr nodejs
    import_role:
      name: common
      tasks_from: nodejs
  - name: add system user
    import_role:
      name: common
      tasks_from: add_user
 
  - name: add and remove directory
    import_role:
    tasks_from: add_remove

  - name: install dependencies
    community.general.npm:
      path: /app 
  - name: copy the servic file
    import_role:
      name: common
      tasks_from: servicefilecopy
  - name: daemon_reload
    import_role: 
      name: common
      tasks_from: demon_servic

