  - name: import thr nodejs
    import_role:
      name: common
      tasks_from: nodejs
  - name: add system user
    import_role:
      name: common
      tasks_from: add_user
 
  - name: add and remove directory
    import_role:
    tasks_from: add_remove

  - name: install dependencies
    community.general.npm:
      path: /app
  - name: copy the servic file
    import_role:
      name: common
      tasks_from: servicefilecopy
  - name: copy the mongo repo
    copy: 
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongo clint
    package:
      name: mongodb-mongosh
      state: present
  - name: check catalogue schema exist ot not
    shell: mongosh --host "{{ MONGODB_HOST }}" --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output
    tags:
    - mongodb
  - name: print catalogue_output
    debug: 
      msg: "{{ catalogue_output }}"
    tags:
    - mongodb
  - name: load products
    shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: catalogue_output.stdout | int < 0
    tags:
    - mongodb
  - name: daemon_reload
    import_role: 
      name: common
      tasks_from: demon_servic

